### PR TITLE
Clippy updated to 0.0.42 and new_ret_no_self allowed

### PR DESCRIPTION
**Pull request by kiriost**
Some changes because playform couldn't be compiled with new rust nightly

### CODE REVIEW

**Comment by bfops** [comment]
Cool, thanks. I'm glad clippy's building again! I'll probably re-disable the `new_ret_no_self` and fix the warnings at some point, since it seems like a fair thing to complain about.

**Comment by bfops** [comment]
Build is broken :(

**Comment by kiriost** [comment]
`cube_shell.rs:160:3: 162:4 error: adding items after statements is confusing, since items exist from the start of the scope, #[deny(items_after_statements)] on by default`

You should "#![allow(items_after_statements)]". Clippy is denying some important things.

**Comment by bfops** [comment]
Okay, I'll just merge this and finish fixing the build.

**Comment by bfops** [comment]
Fixed!

**Pull request merged**
